import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "../components/providers";
import StoreNavBar from "../components/navbar/index";
import Footer from "../components/layout/Footer";
import AuthModals from "../components/auth/AuthModals";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <div className="bg-gray-600 min-h-screen">
            <StoreNavBar />
            <main>{children}</main>
            <Footer />
            <AuthModals />
          </div>
        </Providers>
      </body>
    </html>
  );
}

